version: 2

models:
  - name: products_summary
    columns:
      - name: department
        tests:
          - not_null
      - name: category
        tests:
          - not_null
      - name: avg_profit
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: total_profit
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: num_of_products
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
