dbt_ecommerce_demo:
  outputs:
    dev:
      dataset: dbt_ecommerce
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dbt-learning-429901
      threads: 1
      type: bigquery
  target: dev